import type { MessageKey_defaultSet } from "keycloakify/login";

// Arnold Schwarzenegger's language, because why not?

const messages: Record<MessageKey_defaultSet, string> = {
    // cspell: disable
    doLogIn: "GET TO THE CHOPPAH",
    doRegister: "JOIN ME IF YOU WANT TO LIVE",
    doRegisterSecurityKey: "ENHANCE YOUR SECURITY, NOW",
    doCancel: "TERMINATE",
    doSubmit: "DO IT NOW",
    doBack: "GET TO DA BACK",
    doYes: "YAAAAH",
    doNo: "NO",
    doContinue: "COME WITH ME IF YOU WANT TO LIVE",
    doIgnore: "IT'S NOT A TUMOR",
    doAccept: "I ACCEPT",
    doDecline: "I DECLINE",
    doForgotPassword: "YOU FORGOT YOUR PASSWORD? HOW COULD YOU DO DIS TO ME?",
    doClickHere: "CLICK HERE",
    doImpersonate: "I AM YOUR SUPERIOR NOW",
    doTryAgain: "TRY AGAIN, IF YOU WANT TO LIVE",
    doTryAnotherWay: "TRY ANOTHER WAY",
    doConfirmDelete: "CONFIRM DELETION",
    errorDeletingAccount: "SOMETHING WENT WRONG WHILE DELETING YOUR ACCOUNT",
    deletingAccountForbidden:
        "YOU DO NOT HAVE ENOUGH PERMISSIONS TO DELETE YOUR OWN ACCOUNT. CONTACT YOUR ADMINISTRATOR.",
    kerberosNotConfigured: "KERBEROS IS NOT CONFIGURED",
    kerberosNotConfiguredTitle: "KERBEROS IS NOT CONFIGURED",
    bypassKerberosDetail:
        "EITHER YOU ARE NOT LOGGED IN BY KERBEROS OR YOUR BROWSER IS NOT SET UP FOR KERBEROS LOGIN. CLICK CONTINUE TO LOG IN THROUGH OTHER MEANS.",
    kerberosNotSetUp: "KERBEROS IS NOT SET UP. YOU CANNOT LOGIN.",
    registerTitle: "REGISTER",
    loginAccountTitle: "WHO ARE YOU? SHOW ME YOUR CREDENTIALS.",
    loginTitle: "SIGN IN TO {0}",
    loginTitleHtml: "{0}",
    impersonateTitle: "{0} IMPERSONATE USER",
    impersonateTitleHtml: "<strong>{0}</strong> IMPERSONATE USER",
    realmChoice: "REALM",
    unknownUser: "UNKNOWN USER. WHO SENT YOU?",
    loginTotpTitle: "MOBILE AUTHENTICATOR SETUP",
    loginProfileTitle: "UPDATE ACCOUNT INFORMATION",
    loginIdpReviewProfileTitle: "UPDATE ACCOUNT INFORMATION",
    loginTimeout: "YOUR LOGIN ATTEMPT TIMED OUT. WE HAVE TO GO BACK TO DA BEGINNING.",
    reauthenticate: "PROVE IT'S REALLY YOU. RE-AUTHENTICATE TO CONTINUE.",
    authenticateStrong: "STRONG AUTHENTICATION REQUIRED. YOU ARE NOT STRONG ENOUGH YET.",
    oauthGrantTitle: "GRANT ACCESS TO {0}",
    oauthGrantTitleHtml: "{0}",
    oauthGrantInformation: "MAKE SURE YOU TRUST {0} BY LEARNING HOW {0} WILL HANDLE YOUR DATA.",
    oauthGrantReview: "YOU COULD REVIEW THE ",
    oauthGrantTos: "TERMS OF SERVICE.",
    oauthGrantPolicy: "PRIVACY POLICY.",
    errorTitle: "BIG MISTAKE. BIG. HUGE.",
    errorTitleHtml: "BIG <strong>MISTAKE</strong>. BIG. HUGE.",
    emailVerifyTitle: "EMAIL VERIFICATION",
    emailForgotTitle: "YOU FORGOT YOUR PASSWORD? HOW COULD YOU DO DIS TO ME?",
    updateEmailTitle: "UPDATE EMAIL",
    emailUpdateConfirmationSentTitle: "CONFIRMATION EMAIL SENT",
    emailUpdateConfirmationSent:
        "A CONFIRMATION EMAIL HAS BEEN SENT TO {0}. YOU MUST FOLLOW THE INSTRUCTIONS TO COMPLETE THE EMAIL UPDATE.",
    emailUpdatedTitle: "EMAIL UPDATED",
    emailUpdated: "THE ACCOUNT EMAIL HAS BEEN SUCCESSFULLY UPDATED TO {0}.",
    updatePasswordTitle: "UPDATE PASSWORD",
    codeSuccessTitle: "SUCCESS CODE",
    codeErrorTitle: "ERROR CODE: {0}",
    displayUnsupported: "REQUESTED DISPLAY TYPE UNSUPPORTED",
    browserRequired: "YOU NEED A BROWSER. GET ONE NOW.",
    browserContinue: "BROWSER REQUIRED TO COMPLETE LOGIN. DO NOT STOP NOW.",
    browserContinuePrompt: "OPEN BROWSER AND CONTINUE LOGIN? [y/n]:",
    browserContinueAnswer: "y",
    usb: "USB",
    nfc: "NFC",
    bluetooth: "BLUETOOTH",
    internal: "INTERNAL",
    unknown: "UNKNOWN",
    termsTitle: "TERMS AND CONDITIONS",
    termsText: "",
    termsPlainText: "TERMS AND CONDITIONS TO BE DEFINED.",
    termsAcceptanceRequired: "YOU MUST AGREE TO OUR TERMS AND CONDITIONS. THAT IS AN ORDER.",
    acceptTerms: "I AGREE TO THE TERMS AND CONDITIONS",
    deleteCredentialTitle: "DELETE {0}",
    deleteCredentialMessage: "DO YOU WANT TO DESTROY {0}? DO IT NOW!",
    recaptchaFailed: "YOU ARE NOT HUMAN ENOUGH. TRY AGAIN.",
    recaptchaNotConfigured: "RECAPTCHA IS REQUIRED, BUT NOT CONFIGURED",
    consentDenied: "CONSENT DENIED. TALK TO THE HAND.",
    noAccount: "NEW HERE? DON'T BE A GIRLIE MAN!",
    username: "USERNAME",
    usernameOrEmail: "USERNAME OR EMAIL",
    firstName: "FIRST NAME",
    givenName: "GIVEN NAME",
    fullName: "FULL NAME",
    lastName: "LAST NAME",
    familyName: "FAMILY NAME",
    email: "EMAIL",
    password: "PASSWORD",
    passwordConfirm: "CONFIRM PASSWORD",
    passwordNew: "NEW PASSWORD",
    passwordNewConfirm: "NEW PASSWORD CONFIRMATION",
    hidePassword: "HIDE PASSWORD",
    showPassword: "SHOW PASSWORD. STICK AROUND.",
    rememberMe: "REMEMBER ME. I'LL BE BACK.",
    authenticatorCode: "ONE-TIME CODE",
    address: "ADDRESS",
    street: "STREET",
    locality: "CITY OR LOCALITY",
    region: "STATE, PROVINCE, OR REGION",
    postal_code: "ZIP OR POSTAL CODE",
    country: "COUNTRY",
    emailVerified: "EMAIL VERIFIED",
    website: "WEB PAGE",
    phoneNumber: "PHONE NUMBER",
    phoneNumberVerified: "PHONE NUMBER VERIFIED",
    gender: "GENDER",
    birthday: "BIRTHDATE",
    zoneinfo: "TIME ZONE",
    gssDelegationCredential: "GSS DELEGATION CREDENTIAL",
    logoutOtherSessions: "SIGN OUT FROM OTHER DEVICES",
    profileScopeConsentText: "USER PROFILE",
    emailScopeConsentText: "EMAIL ADDRESS",
    addressScopeConsentText: "ADDRESS",
    phoneScopeConsentText: "PHONE NUMBER",
    offlineAccessScopeConsentText: "OFFLINE ACCESS",
    samlRoleListScopeConsentText: "MY ROLES",
    rolesScopeConsentText: "USER ROLES",
    organizationScopeConsentText: "ORGANIZATION",
    restartLoginTooltip: "RESTART LOGIN",
    loginTotpIntro: "YOU NEED TO SET UP A ONE TIME PASSWORD GENERATOR TO ACCESS THIS ACCOUNT",
    loginTotpStep1: "INSTALL ONE OF THE FOLLOWING APPLICATIONS ON YOUR MOBILE:",
    loginTotpStep2: "OPEN THE APPLICATION AND SCAN THE BARCODE:",
    loginTotpStep3:
        "ENTER THE ONE-TIME CODE PROVIDED BY THE APPLICATION AND CLICK SUBMIT TO FINISH THE SETUP.",
    loginTotpStep3DeviceName: "PROVIDE A DEVICE NAME TO HELP YOU MANAGE YOUR OTP DEVICES.",
    loginTotpManualStep2: "OPEN THE APPLICATION AND ENTER THE KEY:",
    loginTotpManualStep3:
        "USE THE FOLLOWING CONFIGURATION VALUES IF THE APPLICATION ALLOWS SETTING THEM:",
    loginTotpUnableToScan: "UNABLE TO SCAN?",
    loginTotpScanBarcode: "SCAN BARCODE?",
    loginCredential: "CREDENTIAL",
    loginOtpOneTime: "ONE-TIME CODE",
    loginTotpType: "TYPE",
    loginTotpAlgorithm: "ALGORITHM",
    loginTotpDigits: "DIGITS",
    loginTotpInterval: "INTERVAL",
    loginTotpCounter: "COUNTER",
    loginTotpDeviceName: "DEVICE NAME",
    "loginTotp.totp": "TIME-BASED",
    "loginTotp.hotp": "COUNTER-BASED",
    totpAppFreeOTPName: "FREEOTP",
    totpAppGoogleName: "GOOGLE AUTHENTICATOR",
    totpAppMicrosoftAuthenticatorName: "MICROSOFT AUTHENTICATOR",
    loginChooseAuthenticator: "SELECT LOGIN METHOD",
    oauthGrantRequest: "DO YOU GRANT THESE ACCESS PRIVILEGES?",
    inResource: "IN",
    oauth2DeviceVerificationTitle: "DEVICE LOGIN",
    verifyOAuth2DeviceUserCode: "ENTER THE CODE PROVIDED BY YOUR DEVICE AND CLICK SUBMIT",
    oauth2DeviceInvalidUserCodeMessage: "INVALID CODE. PLEASE TRY AGAIN.",
    oauth2DeviceExpiredUserCodeMessage:
        "THE CODE HAS EXPIRED. PLEASE GO BACK TO YOUR DEVICE AND TRY CONNECTING AGAIN.",
    oauth2DeviceVerificationCompleteHeader: "DEVICE LOGIN SUCCESSFUL",
    oauth2DeviceVerificationCompleteMessage:
        "YOU MAY CLOSE THIS BROWSER WINDOW AND GO BACK TO YOUR DEVICE.",
    oauth2DeviceVerificationFailedHeader: "DEVICE LOGIN FAILED",
    oauth2DeviceVerificationFailedMessage:
        "YOU MAY CLOSE THIS BROWSER WINDOW AND GO BACK TO YOUR DEVICE AND TRY CONNECTING AGAIN.",
    oauth2DeviceConsentDeniedMessage: "CONSENT DENIED FOR CONNECTING THE DEVICE.",
    oauth2DeviceAuthorizationGrantDisabledMessage:
        "CLIENT IS NOT ALLOWED TO INITIATE OAUTH 2.0 DEVICE AUTHORIZATION GRANT. THE FLOW IS DISABLED FOR THE CLIENT.",
    emailVerifyInstruction1:
        "AN EMAIL WITH INSTRUCTIONS TO VERIFY YOUR EMAIL ADDRESS HAS BEEN SENT TO YOUR ADDRESS {0}.",
    emailVerifyInstruction2: "HAVEN'T RECEIVED A VERIFICATION CODE IN YOUR EMAIL?",
    emailVerifyInstruction3: "TO RE-SEND THE EMAIL.",
    emailLinkIdpTitle: "LINK {0}",
    emailLinkIdp1:
        "AN EMAIL WITH INSTRUCTIONS TO LINK {0} ACCOUNT {1} WITH YOUR {2} ACCOUNT HAS BEEN SENT TO YOU.",
    emailLinkIdp2: "HAVEN'T RECEIVED A VERIFICATION CODE IN YOUR EMAIL?",
    emailLinkIdp3: "TO RE-SEND THE EMAIL.",
    emailLinkIdp4: "IF YOU ALREADY VERIFIED THE EMAIL IN A DIFFERENT BROWSER",
    emailLinkIdp5: "TO CONTINUE.",
    backToLogin: "&laquo; BACK TO LOGIN",
    emailInstruction:
        "ENTER YOUR USERNAME OR EMAIL ADDRESS AND I WILL SEND YOU INSTRUCTIONS ON HOW TO CREATE A NEW PASSWORD.",
    emailInstructionUsername:
        "ENTER YOUR USERNAME AND I WILL SEND YOU INSTRUCTIONS ON HOW TO CREATE A NEW PASSWORD.",
    copyCodeInstruction: "PLEASE COPY THIS CODE AND PASTE IT INTO YOUR APPLICATION:",
    pageExpiredTitle: "PAGE HAS EXPIRED",
    pageExpiredMsg1: "TO RESTART THE LOGIN PROCESS",
    pageExpiredMsg2: "TO CONTINUE THE LOGIN PROCESS",
    personalInfo: "PERSONAL INFO:",
    role_admin: "ADMIN",
    "role_realm-admin": "REALM ADMIN",
    "role_create-realm": "CREATE REALM",
    "role_create-client": "CREATE CLIENT",
    "role_view-realm": "VIEW REALM",
    "role_view-users": "VIEW USERS",
    "role_view-applications": "VIEW APPLICATIONS",
    "role_view-clients": "VIEW CLIENTS",
    "role_view-events": "VIEW EVENTS",
    "role_view-identity-providers": "VIEW IDENTITY PROVIDERS",
    "role_manage-realm": "MANAGE REALM",
    "role_manage-users": "MANAGE USERS",
    "role_manage-applications": "MANAGE APPLICATIONS",
    "role_manage-identity-providers": "MANAGE IDENTITY PROVIDERS",
    "role_manage-clients": "MANAGE CLIENTS",
    "role_manage-events": "MANAGE EVENTS",
    "role_view-profile": "VIEW PROFILE",
    "role_manage-account": "MANAGE ACCOUNT",
    "role_manage-account-links": "MANAGE ACCOUNT LINKS",
    "role_read-token": "READ TOKEN",
    "role_offline-access": "OFFLINE ACCESS",
    client_account: "ACCOUNT",
    "client_account-console": "ACCOUNT CONSOLE",
    "client_security-admin-console": "SECURITY ADMIN CONSOLE",
    "client_admin-cli": "ADMIN CLI",
    "client_realm-management": "REALM MANAGEMENT",
    client_broker: "BROKER",
    requiredFields: "REQUIRED FIELDS",
    invalidUserMessage: "WRONG USERNAME OR PASSWORD. YOU HAVE BEEN DENIED.",
    invalidUsernameMessage: "THAT USERNAME DOES NOT EXIST. WHO ARE YOU?",
    invalidUsernameOrEmailMessage: "INVALID USERNAME OR EMAIL. I CANNOT FIND YOU.",
    invalidPasswordMessage: "WRONG PASSWORD. YOU LACK DISCIPLINE.",
    invalidEmailMessage: "INVALID EMAIL ADDRESS.",
    accountDisabledMessage: "YOUR ACCOUNT HAS BEEN TERMINATED BY YOUR ADMINISTRATOR.",
    accountTemporarilyDisabledMessage:
        "YOUR ACCOUNT IS TEMPORARILY TERMINATED. CONTACT YOUR ADMINISTRATOR OR RETRY LATER.",
    expiredCodeMessage: "YOUR CODE HAS BEEN TERMINATED. PLEASE SIGN IN AGAIN.",
    expiredActionMessage: "ACTION EXPIRED. YOU WERE TOO SLOW. PLEASE CONTINUE WITH LOGIN NOW.",
    expiredActionTokenNoSessionMessage: "ACTION EXPIRED. HASTA LA VISTA.",
    expiredActionTokenSessionExistsMessage: "ACTION EXPIRED. PLEASE START AGAIN. I'LL WAIT.",
    sessionLimitExceeded: "TOO MANY SESSIONS! CONSIDER THAT A DIVORCE.",
    identityProviderLogoutFailure: "SAML IDP LOGOUT FAILURE",
    missingFirstNameMessage: "WHAT IS YOUR FIRST NAME? TELL ME NOW.",
    missingLastNameMessage: "WHAT IS YOUR LAST NAME? TELL ME NOW.",
    missingEmailMessage: "WHERE IS YOUR EMAIL? DON'T BE A GIRLIE MAN.",
    missingUsernameMessage: "WHERE IS YOUR USERNAME? I NEED TO KNOW.",
    missingPasswordMessage: "WHERE IS YOUR PASSWORD? DON'T BE A GIRLIE MAN.",
    missingTotpMessage: "WHERE IS YOUR AUTHENTICATOR CODE? GIVE IT TO ME NOW.",
    missingTotpDeviceNameMessage: "PLEASE SPECIFY DEVICE NAME.",
    notMatchPasswordMessage: "YOUR PASSWORDS DON'T MATCH. STICK AROUND AND TRY AGAIN.",
    "error-invalid-value": "INVALID VALUE.",
    "error-invalid-blank": "PLEASE SPECIFY VALUE.",
    "error-empty": "PLEASE SPECIFY VALUE.",
    "error-invalid-length": "LENGTH MUST BE BETWEEN {1} AND {2}.",
    "error-invalid-length-too-short": "MINIMAL LENGTH IS {1}.",
    "error-invalid-length-too-long": "MAXIMAL LENGTH IS {2}.",
    "error-invalid-email": "INVALID EMAIL ADDRESS.",
    "error-invalid-number": "INVALID NUMBER.",
    "error-number-out-of-range": "NUMBER MUST BE BETWEEN {1} AND {2}.",
    "error-number-out-of-range-too-small": "NUMBER MUST HAVE MINIMAL VALUE OF {1}.",
    "error-number-out-of-range-too-big": "NUMBER MUST HAVE MAXIMAL VALUE OF {2}.",
    "error-pattern-no-match": "INVALID VALUE.",
    "error-invalid-uri": "INVALID URL.",
    "error-invalid-uri-scheme": "INVALID URL SCHEME.",
    "error-invalid-uri-fragment": "INVALID URL FRAGMENT.",
    "error-user-attribute-required": "PLEASE SPECIFY THIS FIELD.",
    "error-invalid-date": "INVALID DATE.",
    "error-user-attribute-read-only": "THIS FIELD IS READ ONLY.",
    "error-username-invalid-character": "VALUE CONTAINS INVALID CHARACTER.",
    "error-person-name-invalid-character": "VALUE CONTAINS INVALID CHARACTER.",
    "error-reset-otp-missing-id": "PLEASE CHOOSE AN OTP CONFIGURATION.",
    invalidPasswordExistingMessage: "THAT IS NOT YOUR CURRENT PASSWORD. YOU HAVE BEEN CAUGHT.",
    invalidPasswordBlacklistedMessage: "THAT PASSWORD IS ON THE LIST. IT HAS BEEN TERMINATED.",
    invalidPasswordConfirmMessage: "PASSWORD CONFIRMATION DOESN'T MATCH. YOU CANNOT FOOL ME.",
    invalidTotpMessage: "THAT AUTHENTICATOR CODE IS WRONG. YOU ARE NOT WHO YOU CLAIM TO BE.",
    usernameExistsMessage: "THAT USERNAME IS ALREADY TAKEN. SOMEONE WAS FASTER THAN YOU.",
    emailExistsMessage: "THAT EMAIL ALREADY EXISTS. ARE YOU A CLONE?",
    federatedIdentityExistsMessage:
        "USER WITH {0} {1} ALREADY EXISTS. PLEASE LOGIN TO ACCOUNT MANAGEMENT TO LINK THE ACCOUNT.",
    federatedIdentityUnavailableMessage:
        "USER {0} AUTHENTICATED WITH IDENTITY PROVIDER {1} DOES NOT EXIST. PLEASE CONTACT YOUR ADMINISTRATOR.",
    federatedIdentityUnmatchedEssentialClaimMessage:
        "THE ID TOKEN ISSUED BY THE IDENTITY PROVIDER DOES NOT MATCH THE CONFIGURED ESSENTIAL CLAIM. PLEASE CONTACT YOUR ADMINISTRATOR.",
    confirmLinkIdpTitle: "ACCOUNT ALREADY EXISTS",
    confirmOverrideIdpTitle: "BROKER LINK ALREADY EXISTS",
    federatedIdentityConfirmLinkMessage:
        "USER WITH {0} {1} ALREADY EXISTS. HOW DO YOU WANT TO CONTINUE?",
    federatedIdentityConfirmOverrideMessage:
        "YOU ARE TRYING TO LINK YOUR ACCOUNT {0} WITH THE {1} ACCOUNT {2}. BUT YOUR ACCOUNT IS ALREADY LINKED WITH A DIFFERENT {3} ACCOUNT {4}. DO YOU WANT TO REPLACE THE EXISTING LINK WITH THE NEW ACCOUNT?",
    federatedIdentityConfirmReauthenticateMessage: "AUTHENTICATE TO LINK YOUR ACCOUNT WITH {0}",
    nestedFirstBrokerFlowMessage: "THE {0} USER {1} IS NOT LINKED TO ANY KNOWN USER.",
    confirmLinkIdpReviewProfile: "REVIEW PROFILE",
    confirmLinkIdpContinue: "ADD TO EXISTING ACCOUNT",
    confirmOverrideIdpContinue: "YES, OVERRIDE LINK WITH CURRENT ACCOUNT",
    configureTotpMessage: "YOU NEED TO SET UP MOBILE AUTHENTICATOR TO ACTIVATE YOUR ACCOUNT.",
    configureBackupCodesMessage: "YOU NEED TO SET UP BACKUP CODES TO ACTIVATE YOUR ACCOUNT.",
    updateProfileMessage: "YOU NEED TO UPDATE YOUR USER PROFILE TO ACTIVATE YOUR ACCOUNT.",
    updatePasswordMessage: "YOU NEED TO CHANGE YOUR PASSWORD TO ACTIVATE YOUR ACCOUNT.",
    updateEmailMessage: "YOU NEED TO UPDATE YOUR EMAIL ADDRESS TO ACTIVATE YOUR ACCOUNT.",
    resetPasswordMessage: "YOU NEED TO CHANGE YOUR PASSWORD.",
    verifyEmailMessage: "YOU NEED TO VERIFY YOUR EMAIL ADDRESS TO ACTIVATE YOUR ACCOUNT.",
    linkIdpMessage: "YOU NEED TO VERIFY YOUR EMAIL ADDRESS TO LINK YOUR ACCOUNT WITH {0}.",
    emailSentMessage: "I SENT THE EMAIL. IT WILL FIND YOU. I ALWAYS DO.",
    emailSendErrorMessage: "THE EMAIL COULD NOT BE SENT. I'LL TRY AGAIN LATER.",
    accountUpdatedMessage: "YOUR ACCOUNT IS NOW STRONGER THAN EVER.",
    accountPasswordUpdatedMessage: "YOUR NEW PASSWORD IS LIKE STEEL. WELL DONE.",
    delegationCompleteHeader: "LOGIN SUCCESSFUL",
    delegationCompleteMessage:
        "YOU MAY CLOSE THIS BROWSER WINDOW AND GO BACK TO YOUR CONSOLE APPLICATION.",
    delegationFailedHeader: "LOGIN FAILED",
    delegationFailedMessage:
        "YOU MAY CLOSE THIS BROWSER WINDOW AND GO BACK TO YOUR CONSOLE APPLICATION AND TRY LOGGING IN AGAIN.",
    noAccessMessage: "YOU SHALL NOT PASS. NO ACCESS.",
    invalidPasswordMinLengthMessage: "YOUR PASSWORD IS TOO SHORT. PUMP IT UP. MINIMUM LENGTH {0}.",
    invalidPasswordMaxLengthMessage: "YOUR PASSWORD IS TOO LONG. TRIM IT DOWN. MAXIMUM LENGTH {0}.",
    invalidPasswordMinDigitsMessage: "YOUR PASSWORD NEEDS MORE DIGITS. AT LEAST {0} NUMERICAL DIGITS.",
    invalidPasswordMinLowerCaseCharsMessage:
        "YOUR PASSWORD NEEDS MORE LOWER CASE. AT LEAST {0} LOWER CASE CHARACTERS.",
    invalidPasswordMinUpperCaseCharsMessage:
        "YOUR PASSWORD NEEDS MORE UPPER CASE. AT LEAST {0} UPPER CASE CHARACTERS.",
    invalidPasswordMinSpecialCharsMessage:
        "YOUR PASSWORD NEEDS SPECIAL CHARACTERS. AT LEAST {0} SPECIAL CHARACTERS.",
    invalidPasswordNotUsernameMessage: "YOUR PASSWORD CANNOT BE YOUR USERNAME. DO NOT BE PREDICTABLE.",
    invalidPasswordNotContainsUsernameMessage: "INVALID PASSWORD: CANNOT CONTAIN THE USERNAME.",
    invalidPasswordNotEmailMessage: "YOUR PASSWORD CANNOT BE YOUR EMAIL. DO NOT BE PREDICTABLE.",
    invalidPasswordRegexPatternMessage: "INVALID PASSWORD: FAILS TO MATCH REGEX PATTERN(S).",
    invalidPasswordHistoryMessage: "YOU USED THAT PASSWORD BEFORE. MUST NOT BE EQUAL TO ANY OF LAST {0} PASSWORDS.",
    invalidPasswordGenericMessage: "THAT PASSWORD IS NOT GOOD ENOUGH. IT DOESN'T MATCH OUR POLICIES.",
    failedToProcessResponseMessage: "FAILED TO PROCESS RESPONSE",
    httpsRequiredMessage: "HTTPS REQUIRED. SECURITY FIRST.",
    realmNotEnabledMessage: "THIS REALM HAS BEEN TERMINATED.",
    invalidRequestMessage: "INVALID REQUEST",
    successLogout: "HASTA LA VISTA, BABY. YOU ARE NOW LOGGED OUT.",
    failedLogout: "LOGOUT FAILED. I CANNOT BE TERMINATED.",
    unknownLoginRequesterMessage: "UNKNOWN LOGIN REQUESTER",
    loginRequesterNotEnabledMessage: "LOGIN REQUESTER NOT ENABLED",
    bearerOnlyMessage: "BEARER-ONLY APPLICATIONS ARE NOT ALLOWED TO INITIATE BROWSER LOGIN",
    standardFlowDisabledMessage:
        "CLIENT IS NOT ALLOWED TO INITIATE BROWSER LOGIN WITH GIVEN RESPONSE_TYPE. STANDARD FLOW IS DISABLED FOR THE CLIENT.",
    implicitFlowDisabledMessage:
        "CLIENT IS NOT ALLOWED TO INITIATE BROWSER LOGIN WITH GIVEN RESPONSE_TYPE. IMPLICIT FLOW IS DISABLED FOR THE CLIENT.",
    invalidRedirectUriMessage: "INVALID REDIRECT URI",
    unsupportedNameIdFormatMessage: "UNSUPPORTED NAMEIDFORMAT",
    invalidRequesterMessage: "INVALID REQUESTER",
    registrationNotAllowedMessage: "REGISTRATION NOT ALLOWED",
    resetCredentialNotAllowedMessage: "RESET CREDENTIAL NOT ALLOWED",
    permissionNotApprovedMessage: "PERMISSION NOT APPROVED.",
    noRelayStateInResponseMessage: "NO RELAY STATE IN RESPONSE FROM IDENTITY PROVIDER.",
    insufficientPermissionMessage: "INSUFFICIENT PERMISSIONS TO LINK IDENTITIES.",
    couldNotProceedWithAuthenticationRequestMessage:
        "COULD NOT PROCEED WITH AUTHENTICATION REQUEST TO IDENTITY PROVIDER.",
    couldNotObtainTokenMessage: "COULD NOT OBTAIN TOKEN FROM IDENTITY PROVIDER.",
    unexpectedErrorRetrievingTokenMessage:
        "UNEXPECTED ERROR WHEN RETRIEVING TOKEN FROM IDENTITY PROVIDER.",
    unexpectedErrorHandlingResponseMessage:
        "UNEXPECTED ERROR WHEN HANDLING RESPONSE FROM IDENTITY PROVIDER.",
    identityProviderAuthenticationFailedMessage:
        "AUTHENTICATION FAILED. COULD NOT AUTHENTICATE WITH IDENTITY PROVIDER.",
    couldNotSendAuthenticationRequestMessage:
        "COULD NOT SEND AUTHENTICATION REQUEST TO IDENTITY PROVIDER.",
    unexpectedErrorHandlingRequestMessage:
        "UNEXPECTED ERROR WHEN HANDLING AUTHENTICATION REQUEST TO IDENTITY PROVIDER.",
    invalidAccessCodeMessage: "INVALID ACCESS CODE.",
    sessionNotActiveMessage: "SESSION NOT ACTIVE.",
    invalidCodeMessage: "AN ERROR OCCURRED. PLEASE LOGIN AGAIN THROUGH YOUR APPLICATION.",
    cookieNotFoundMessage: "COOKIE NOT FOUND. PLEASE MAKE SURE COOKIES ARE ENABLED IN YOUR BROWSER.",
    insufficientLevelOfAuthentication: "THE REQUESTED LEVEL OF AUTHENTICATION HAS NOT BEEN SATISFIED.",
    identityProviderUnexpectedErrorMessage:
        "UNEXPECTED ERROR WHEN AUTHENTICATING WITH IDENTITY PROVIDER",
    identityProviderMissingStateMessage: "MISSING STATE PARAMETER IN RESPONSE FROM IDENTITY PROVIDER.",
    identityProviderMissingCodeOrErrorMessage:
        "MISSING CODE OR ERROR PARAMETER IN RESPONSE FROM IDENTITY PROVIDER.",
    identityProviderInvalidResponseMessage: "INVALID RESPONSE FROM IDENTITY PROVIDER.",
    identityProviderInvalidSignatureMessage: "INVALID SIGNATURE IN RESPONSE FROM IDENTITY PROVIDER.",
    identityProviderNotFoundMessage: "COULD NOT FIND AN IDENTITY PROVIDER WITH THE IDENTIFIER.",
    identityProviderLinkSuccess:
        "YOU SUCCESSFULLY VERIFIED YOUR EMAIL. PLEASE GO BACK TO YOUR ORIGINAL BROWSER AND CONTINUE THERE WITH THE LOGIN.",
    staleCodeMessage:
        "THIS PAGE IS NO LONGER VALID. PLEASE GO BACK TO YOUR APPLICATION AND SIGN IN AGAIN.",
    realmSupportsNoCredentialsMessage: "REALM DOES NOT SUPPORT ANY CREDENTIAL TYPE.",
    credentialSetupRequired: "CANNOT LOGIN. CREDENTIAL SETUP REQUIRED.",
    identityProviderNotUniqueMessage:
        "REALM SUPPORTS MULTIPLE IDENTITY PROVIDERS. COULD NOT DETERMINE WHICH IDENTITY PROVIDER SHOULD BE USED TO AUTHENTICATE WITH.",
    emailVerifiedMessage: "YOUR EMAIL ADDRESS HAS BEEN VERIFIED.",
    emailVerifiedAlreadyMessage: "YOUR EMAIL ADDRESS HAS BEEN VERIFIED ALREADY.",
    staleEmailVerificationLink:
        "THE LINK YOU CLICKED IS AN OLD STALE LINK AND IS NO LONGER VALID. MAYBE YOU HAVE ALREADY VERIFIED YOUR EMAIL.",
    identityProviderAlreadyLinkedMessage:
        "FEDERATED IDENTITY RETURNED BY {0} IS ALREADY LINKED TO ANOTHER USER.",
    confirmAccountLinking: "CONFIRM LINKING THE ACCOUNT {0} OF IDENTITY PROVIDER {1} WITH YOUR ACCOUNT.",
    confirmEmailAddressVerification: "CONFIRM VALIDITY OF E-MAIL ADDRESS {0}.",
    confirmExecutionOfActions: "PERFORM THE FOLLOWING ACTION(S)",
    backToApplication: "&laquo; BACK TO APPLICATION",
    missingParameterMessage: "MISSING PARAMETERS: {0}",
    clientNotFoundMessage: "CLIENT NOT FOUND.",
    clientDisabledMessage: "CLIENT DISABLED.",
    invalidParameterMessage: "INVALID PARAMETER: {0}",
    alreadyLoggedIn: "YOU ARE ALREADY LOGGED IN.",
    differentUserAuthenticated:
        "YOU ARE ALREADY AUTHENTICATED AS DIFFERENT USER '{0}' IN THIS SESSION. PLEASE SIGN OUT FIRST.",
    brokerLinkingSessionExpired:
        "REQUESTED BROKER ACCOUNT LINKING, BUT CURRENT SESSION IS NO LONGER VALID.",
    proceedWithAction: "&raquo; CLICK HERE TO PROCEED",
    acrNotFulfilled: "AUTHENTICATION REQUIREMENTS NOT FULFILLED",
    "requiredAction.CONFIGURE_TOTP": "CONFIGURE OTP",
    "requiredAction.TERMS_AND_CONDITIONS": "TERMS AND CONDITIONS",
    "requiredAction.UPDATE_PASSWORD": "UPDATE PASSWORD",
    "requiredAction.UPDATE_PROFILE": "UPDATE PROFILE",
    "requiredAction.VERIFY_EMAIL": "VERIFY EMAIL",
    "requiredAction.CONFIGURE_RECOVERY_AUTHN_CODES": "GENERATE RECOVERY CODES",
    "requiredAction.webauthn-register-passwordless": "WEBAUTHN REGISTER PASSWORDLESS",
    invalidTokenRequiredActions: "REQUIRED ACTIONS INCLUDED IN THE LINK ARE NOT VALID",
    doX509Login: "YOU WILL BE LOGGED IN AS:",
    clientCertificate: "X509 CLIENT CERTIFICATE:",
    noCertificate: "[NO CERTIFICATE]",
    pageNotFound: "THIS PAGE HAS BEEN TERMINATED",
    internalServerError: "THE SERVER MADE A BIG MISTAKE. I AM VERY DISAPPOINTED.",
    "console-username": "USERNAME:",
    "console-password": "PASSWORD:",
    "console-otp": "ONE TIME PASSWORD:",
    "console-new-password": "NEW PASSWORD:",
    "console-confirm-password": "CONFIRM PASSWORD:",
    "console-update-password": "UPDATE OF YOUR PASSWORD IS REQUIRED.",
    "console-verify-email":
        "YOU NEED TO VERIFY YOUR EMAIL ADDRESS. WE SENT AN EMAIL TO {0} THAT CONTAINS A VERIFICATION CODE. PLEASE ENTER THIS CODE INTO THE INPUT BELOW.",
    "console-email-code": "EMAIL CODE:",
    "console-accept-terms": "ACCEPT TERMS? [y/n]:",
    "console-accept": "y",
    "openshift.scope.user_info": "USER INFORMATION",
    "openshift.scope.user_check-access": "USER ACCESS INFORMATION",
    "openshift.scope.user_full": "FULL ACCESS",
    "openshift.scope.list-projects": "LIST PROJECTS",
    "saml.post-form.title": "AUTHENTICATION REDIRECT",
    "saml.post-form.message": "REDIRECTING, PLEASE WAIT.",
    "saml.post-form.js-disabled":
        "JAVASCRIPT IS DISABLED. I STRONGLY RECOMMEND TO ENABLE IT. CLICK THE BUTTON BELOW TO CONTINUE.",
    "saml.artifactResolutionServiceInvalidResponse": "UNABLE TO RESOLVE ARTIFACT.",
    "otp-display-name": "AUTHENTICATOR APPLICATION",
    "otp-help-text": "ENTER A VERIFICATION CODE FROM AUTHENTICATOR APPLICATION.",
    "otp-reset-description": "WHICH OTP CONFIGURATION SHOULD BE REMOVED?",
    "password-display-name": "PASSWORD",
    "password-help-text": "SIGN IN BY ENTERING YOUR PASSWORD.",
    "auth-username-form-display-name": "USERNAME",
    "auth-username-form-help-text": "START SIGN IN BY ENTERING YOUR USERNAME",
    "auth-username-password-form-display-name": "USERNAME AND PASSWORD",
    "auth-username-password-form-help-text": "SIGN IN BY ENTERING YOUR USERNAME AND PASSWORD.",
    "auth-x509-client-username-form-display-name": "X509 CERTIFICATE",
    "auth-x509-client-username-form-help-text": "SIGN IN WITH AN X509 CLIENT CERTIFICATE.",
    "auth-recovery-authn-code-form-display-name": "RECOVERY AUTHENTICATION CODE",
    "auth-recovery-authn-code-form-help-text":
        "ENTER A RECOVERY AUTHENTICATION CODE FROM A PREVIOUSLY GENERATED LIST.",
    "auth-recovery-code-info-message": "ENTER THE SPECIFIED RECOVERY CODE.",
    "auth-recovery-code-prompt": "RECOVERY CODE #{0}",
    "auth-recovery-code-header": "LOGIN WITH A RECOVERY AUTHENTICATION CODE",
    "recovery-codes-error-invalid": "INVALID RECOVERY AUTHENTICATION CODE",
    "recovery-code-config-header": "RECOVERY AUTHENTICATION CODES",
    "recovery-code-config-warning-title":
        "THESE RECOVERY CODES WON'T APPEAR AGAIN AFTER LEAVING THIS PAGE",
    "recovery-code-config-warning-message":
        "MAKE SURE TO PRINT, DOWNLOAD, OR COPY THEM TO A PASSWORD MANAGER AND KEEP THEM SAFE. CANCELING THIS SETUP WILL REMOVE THESE RECOVERY CODES FROM YOUR ACCOUNT.",
    "recovery-codes-print": "PRINT",
    "recovery-codes-download": "DOWNLOAD",
    "recovery-codes-copy": "COPY",
    "recovery-codes-copied": "COPIED",
    "recovery-codes-confirmation-message": "I HAVE SAVED THESE CODES SOMEWHERE SAFE",
    "recovery-codes-action-complete": "COMPLETE SETUP",
    "recovery-codes-action-cancel": "CANCEL SETUP",
    "recovery-codes-download-file-header": "KEEP THESE RECOVERY CODES SOMEWHERE SAFE.",
    "recovery-codes-download-file-description":
        "RECOVERY CODES ARE SINGLE-USE PASSCODES THAT ALLOW YOU TO SIGN IN TO YOUR ACCOUNT IF YOU DO NOT HAVE ACCESS TO YOUR AUTHENTICATOR.",
    "recovery-codes-download-file-date": "THESE CODES WERE GENERATED ON",
    "recovery-codes-label-default": "RECOVERY CODES",
    "webauthn-display-name": "PASSKEY",
    "webauthn-help-text": "USE YOUR PASSKEY TO SIGN IN.",
    "webauthn-passwordless-display-name": "PASSKEY",
    "webauthn-passwordless-help-text": "USE YOUR PASSKEY FOR PASSWORDLESS SIGN IN.",
    "webauthn-login-title": "PASSKEY LOGIN",
    "webauthn-registration-title": "PASSKEY REGISTRATION",
    "webauthn-available-authenticators": "AVAILABLE PASSKEYS",
    "webauthn-unsupported-browser-text":
        "WEBAUTHN IS NOT SUPPORTED BY THIS BROWSER. TRY ANOTHER ONE OR CONTACT YOUR ADMINISTRATOR.",
    "webauthn-doAuthenticate": "SIGN IN WITH PASSKEY",
    "webauthn-createdAt-label": "CREATED",
    "webauthn-registration-init-label": "PASSKEY (DEFAULT LABEL)",
    "webauthn-registration-init-label-prompt": "PLEASE INPUT YOUR REGISTERED PASSKEY'S LABEL",
    "webauthn-error-title": "PASSKEY ERROR",
    "webauthn-error-registration": "FAILED TO REGISTER YOUR PASSKEY.<br/> {0}",
    "webauthn-error-api-get": "FAILED TO AUTHENTICATE BY THE PASSKEY.<br/> {0}",
    "webauthn-error-different-user":
        "FIRST AUTHENTICATED USER IS NOT THE ONE AUTHENTICATED BY THE PASSKEY.",
    "webauthn-error-auth-verification": "PASSKEY AUTHENTICATION RESULT IS INVALID.<br/> {0}",
    "webauthn-error-register-verification": "PASSKEY REGISTRATION RESULT IS INVALID.<br/> {0}",
    "webauthn-error-user-not-found": "UNKNOWN USER AUTHENTICATED BY THE PASSKEY.",
    "passkey-login-title": "PASSKEY LOGIN",
    "passkey-available-authenticators": "AVAILABLE PASSKEYS",
    "passkey-unsupported-browser-text":
        "PASSKEY IS NOT SUPPORTED BY THIS BROWSER. TRY ANOTHER ONE OR CONTACT YOUR ADMINISTRATOR.",
    "passkey-doAuthenticate": "SIGN IN WITH PASSKEY",
    "passkey-createdAt-label": "CREATED",
    "passkey-autofill-select": "SELECT YOUR PASSKEY",
    "identity-provider-redirector": "CONNECT WITH ANOTHER IDENTITY PROVIDER",
    "identity-provider-login-label": "OR SIGN IN WITH",
    "idp-email-verification-display-name": "EMAIL VERIFICATION",
    "idp-email-verification-help-text": "LINK YOUR ACCOUNT BY VALIDATING YOUR EMAIL.",
    "idp-username-password-form-display-name": "USERNAME AND PASSWORD",
    "idp-username-password-form-help-text": "LINK YOUR ACCOUNT BY LOGGING IN.",
    finalDeletionConfirmation:
        "IF YOU DELETE YOUR ACCOUNT, IT CANNOT BE RESTORED. DON'T DO IT. CLICK CANCEL AND BE BACK INSTEAD.",
    irreversibleAction: "THIS ACTION CANNOT BE UNDONE. IT IS NOT A TUMOR, IT IS PERMANENT.",
    deleteAccountConfirm: "DELETE ACCOUNT? THERE IS NO COMING BACK FROM THIS.",
    deletingImplies: "DELETING YOUR ACCOUNT IMPLIES:",
    errasingData: "ERASING ALL YOUR DATA. YOU HAVE BEEN ERASED.",
    loggingOutImmediately: "LOGGING YOU OUT IMMEDIATELY. I'LL BE BACK, BUT YOU WON'T.",
    accountUnusable: "ANY SUBSEQUENT USE OF THE APPLICATION WILL NOT BE POSSIBLE WITH THIS ACCOUNT",
    userDeletedSuccessfully: "USER DELETED SUCCESSFULLY. YOU HAVE BEEN TERMINATED.",
    "access-denied": "ACCESS DENIED. YOU HAVE NO POWER HERE.",
    "access-denied-when-idp-auth": "ACCESS DENIED WHEN AUTHENTICATING WITH {0}",
    "frontchannel-logout.title": "LOGGING OUT",
    "frontchannel-logout.message": "YOU ARE LOGGING OUT FROM FOLLOWING APPS",
    logoutConfirmTitle: "LOGGING OUT",
    logoutConfirmHeader: "YOU REALLY WANT TO LEAVE? DON'T BE A GIRLIE MAN.",
    doLogout: "I'LL BE BACK",
    readOnlyUsernameMessage: "YOU CAN'T UPDATE YOUR USERNAME AS IT IS READ-ONLY.",
    "error-invalid-multivalued-size": "ATTRIBUTE {0} MUST HAVE AT LEAST {1} AND AT MOST {2} VALUE(S).",
    "organization.confirm-membership.title": "YOU ARE ABOUT TO JOIN ORGANIZATION ${kc.org.name}",
    "organization.confirm-membership":
        "BY CLICKING ON THE LINK BELOW, YOU WILL BECOME A MEMBER OF THE {0} ORGANIZATION:",
    "organization.member.register.title": "CREATE AN ACCOUNT TO JOIN THE ${kc.org.name} ORGANIZATION",
    shouldBeEqual: "{0} SHOULD BE EQUAL TO {1}",
    shouldBeDifferent: "{0} SHOULD BE DIFFERENT TO {1}",
    shouldMatchPattern: "PATTERN SHOULD MATCH: `/{0}/`",
    mustBeAnInteger: "MUST BE AN INTEGER",
    notAValidOption: "NOT A VALID OPTION",
    selectAnOption: "SELECT AN OPTION",
    remove: "REMOVE",
    addValue: "ADD VALUE",
    languages: "LANGUAGES",
    "organization.select": "SELECT AN ORGANIZATION TO PROCEED:",
    linkIdpActionTitle: "LINKING {0}",
    linkIdpActionMessage: "DO YOU WANT TO LINK YOUR ACCOUNT WITH {0}?"
    // cspell: enable
};

export default messages;
